### ISSUE TITLE
抓包格式是怎样的？

### ISSUE THREAD

**Issue by 19961102** [jy03078584/pyplan#1]
问下大佬这个抓包格式是怎样的，我把抓的cookies写进去提示hpv4g.py: error: the following arguments are required: tk, cookie

**Comment by xiangmingzhe0928** [comment]
@19961102 
> `抓包格式是怎样的` 

Hi 老哥 我没太懂你的意思 家里电脑不方便 . 将就看下
- 可以使用 `-h` 参看使用说明：
![image](https://user-images.githubusercontent.com/7719370/93669447-c5f72b00-fac6-11ea-81da-271fa0e8edc8.png)
  - `tk`和`cookie`是必填参数 顺序是固定的 以空格为间隔
***
## 举个例子
- 抓包
![image](https://user-images.githubusercontent.com/7719370/93668994-3ef48380-fac3-11ea-9d3a-6e3a56b81811.png)
- **tk**即为`wxapptoken:10:de185e962abea05b50e4........`
- **cookie**即为`_xxhm_=%7B%22headerImg%22%3A%22http%3A%2F%2Fthirdwx.qlogo.cn%...........` 
   - cookie这里有个小坑 抓出来的cookie里面有多个key之间默认自带了`空格`分割 1.可以在执行传参的时候手动删除下这个空格 2.直接用双引号包裹也可以
- 运行
```
hpv4g.py wxapptoken:10:de185e962abea05b50e4........ _xxhm_=%7B%22headerImg%22%3A%22http%3A%2F%2Fthirdwx.qlogo.cn%...........
```
*** 
这个脚本 我原先只用多线程去执行 后来发现Server有频率限制 还没搞清楚是IP限制还ID限制。现在的版本加了IP代理等下一轮秒杀的时候试试看

**Comment by 19961102** [comment]
试运行了下确实可以，看下次能不能帮女友抢到，谢老哥

**Comment by 19961102** [comment]
刚刚试了下，秒杀界面error occurred502 Server Error: Bad Gateway，不知道是不是秒杀的加密参数又改了

**Comment by xiangmingzhe0928** [comment]
@19961102 
这2天没看这个 要重新抓包看下是不是新增加了参数
